### PR TITLE
React Foundation

### PR DESCRIPTION
**Pull request by toastercup**
Thin wisps of smoke curl out of the bike's treads as it peels out before you; you work your gears and mechanisms and pedal full-speed ahead, finally closing on the beast you've been trailing for weeks. It's treed, and it knows it - _it's finally happening_ - it barrels into the gas station and crashes its doors open, your velocipede, poised and balanced with the perfect, ignorant certainty of a wild animal, in hot pursuit. You round the corner into the shop, the tangerine glare of your headlights scowling menacingly through the shrouding mist at the React Foundation, all shambles and nerves, twisting and retreating instinctively. **And a dark wind blows**. * *flips his hair back* *

Here lies the complementary PR to round out https://github.com/cbdr/cortex/pull/449. What you should know:
* Plugin React components are now wrapped into Node packages, which Cortex picks up on
* Cortex iterates through all plugins and deduces their package names, adding them to the entry points array in its `webpack.config.js`
* Cortex whitelists all `cortex-plugin-*` npm packages to get built by `babel-loader`
* All default `react-on-rails` dependencies are now `peerDependencies`, so they aren't duplicated in the `bundle` and can register with `ReactOnRails`
* Expanded `.gitignore` to more closely match potential Rails engine artifacts

image

### CODE REVIEW

**Comment by jcbostick** [comment]
Are all your PRs strange ass stories? Velocipede, really?

**Comment by toastercup** [comment]
(yes)

**Review by MKwenhua — APPROVED** [review]
Looks good, but why are we including ReactOnRails in both?

**Review by ElliottAYoung — APPROVED** [review]
:+1:

**Comment by toastercup** [comment]
@MKwenhua the default `react-on-rails` dependencies are now listed as `peerDependencies`, so they'll only be loaded in once.

**Review by arelia — APPROVED** [review]

**Pull request merged**
