### PR TITLE
COR-526: Popup Button

### PR DESCRIPTION
**Pull request by ElliottAYoung**
@toastercup @arelia @MKwenhua 

Adds the empty class for ContentItemFieldTypes (only empty for now) and allows for this button to link to the necessary classes to trigger the media popup in Cortex.

### CODE REVIEW

**Review by MKwenhua — CHANGES_REQUESTED** [review]
Change 

```ruby
%button.content_item_button.text-center.popup--open
```

**to:**
```ruby
 .content_item_button.text-center.popup--open
```

that way you wont need to prevent default and it will wont fire any native browser events.

**Comment by toastercup** [comment]
@MKwenhua @ElliottAYoung That suggestion defies the use of semantic elements, however - this is a button and should remain a button, IMO. We shouldn't need to `preventDefault` here because there is no form action associated with this button, nor any other default browser event.

**Review by toastercup — APPROVED** [review]

**Comment by toastercup** [comment]
@ElliottAYoung Remember that the PR naming conventions specify a capitalized title. This is nitpicky, so historically I've gone through and corrected your PRs, but since it's been a recurring thing, I wanted to mention it - esp. if Cortex is going to be open source, we should present a unified standard that all contributors will be held to

**Review by MKwenhua — APPROVED** [review]
On second thought I agree with @toastercup , no need to change the button tag :neckbeard:

**Comment by toastercup** [comment]
@ElliottAYoung FYI for the future, remember to bump the version once you've wrapped up a feature, otherwise it breaks Cortex develop. As maintainers of this lib, we can bump version within a PR, but contributors do not bump version.

**Pull request merged**
